sudo: true
dist: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_e06a3a9321e9_key -iv $encrypted_e06a3a9321e9_iv
  -in travis-ci/server.key.enc -out server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile server.key --username
  $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
